name: Django Tests

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest

        services:
            mssql:
                image: mcr.microsoft.com/mssql/server:2019-latest
                ports:
                    - 1433:1433
                env:
                    SA_PASSWORD: "YourStrong!Passw0rd"
                    ACCEPT_EULA: "Y"
                options: >-
                    --health-cmd "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P YourStrong!Passw0rd -Q 'SELECT 1'"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install django
                  pip install pyodbc
                  pip install mssql-django
                  pip install -r requirements.txt

            - name: Set up Django
              run: |
                  python manage.py migrate
                  python manage.py collectstatic --noinput

            - name: Run tests
              env:
                  DATABASE_URL: mssql://SA:YourStrong!Passw0rd@localhost:1433/Django_db
              run: |
                  python manage.py test
